-- 재구매 회원 ID, 재구매 상품 ID 조회
-- 동일한 회원이 동일한 상품 재구매한 경우
-- 회원 ID 오름차순 & 상품 ID 내림차순

SELECT DISTINCT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID
WHERE A.ONLINE_SALE_ID != B.ONLINE_SALE_ID
ORDER BY A.USER_ID, A.PRODUCT_ID DESC;
