-- 판매 날짜, 상품ID, 유저ID, 판매량
-- 2022년 3월
-- OFFLINE_SALE 테이블의 판매 데이터의 USER_ID 값은 NULL
-- 판매일 오름차순, 상품ID 오름차순, 유저아이디 오름차순

-- 2022/03 온라인
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE BETWEEN DATE('2022-03-01') AND DATE('2022-03-31')
UNION
-- 2022/03 오프라인
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN DATE('2022-03-01') AND DATE('2022-03-31')
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID