-- 회원의 ID, 이름, 성별, 생년월일
-- 여성, 생일 3월
-- 전화번호 null인 경우 제외
-- 회원 ID 기준 오름차순

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND TLNO IS NOT NULL AND SUBSTRING(DATE_OF_BIRTH, 6, 2) = '03'
ORDER BY MEMBER_ID;