-- 중고 거래한 총금액이 70만원 이상인 회원 ID, 닉네임, 총거래금액
-- 총거래금액 오름차순
SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER g
ON b.WRITER_ID = g.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;