
SELECT o.ID, f.FISH_NAME, o.LENGTH
FROM FISH_INFO o LEFT JOIN FISH_NAME_INFO f ON o.FISH_TYPE = f.FISH_TYPE
RIGHT JOIN ( 
    -- 타입별 가장 큰 물고기
    SELECT FISH_NAME, MAX(LENGTH) LENGTH
    FROM FISH_INFO i LEFT JOIN FISH_NAME_INFO n
    ON i.FISH_TYPE = n.FISH_TYPE
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_NAME
) j ON f.FISH_NAME = j.FISH_NAME AND o.LENGTH = j.LENGTH
ORDER BY o.ID