-- 도서 아이디, 출판일
-- 2021년 출판, 인문 카테고리
-- 출판일 오름차순
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND PUBLISHED_DATE BETWEEN DATE('2021-01-01') AND DATE('2021-12-31')
ORDER BY PUBLISHED_DATE;