-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
-- 2022년 10월 작성
-- 댓글 작성일 오름차순, 게시글 제목 오름차순
SELECT b.TITLE, b.BOARD_ID, REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD b JOIN USED_GOODS_REPLY r 
ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE BETWEEN DATE('2022-10-01') AND DATE('2022-10-31')
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;